# Project Background and aims

Quinolone resistance among commensal _E. coli_ from Norwegian food-producing animals is generally low. This is considered to be a consequence of good animal health and of the low usage of quinolones. After the introduction of a selective method in NORM-VET, QREC was detected in a high proportion of samples in broilers and pigs. Because of the low quinolone usage in these animal populations, the observed occurrence was somewhat unexpected and warranted further investigation into the characteristics and the origin of these bacteria. This project provides a unique opportunity to investigate other causes of quinolone resistance development than quinolone usage. Investigating the mechanisms conferring resistance may provide information on whether the majority is plasmid-mediated or chromosomal. This can, in turn, give indications on how the quinolone resistance is disseminated. Insights into the phylogenetic relationship between isolates may reveal information on possible dissemination within or between animal populations. It can also provide indications for persistence in these environments. This information is important to further understand how QREC may be disseminated or developed in animal populations, especially in countries with low antimicrobial usage. Furthermore, these data may be used to implement specific preventive strategies to reduce potential dissemination of QREC within production animal populations. These implementations can help maintain the favourable situation in Norway.

The aims of this study were to:

- Summarize and describe existing data on occurrence of quinolone resistance in animal populations

- Characterize genetic mechanisms that may explain the observed quinolone resistance

- Explore potential emergence and dissemination of quinolone resistance in _E. coli_ in livestock populations
