# Summary of scientific articles

**1. Occurrence of quinolone resistant _E. coli_ originating from different animal species in Norway**

_Håkon Kaspersen, Anne Margrete Urdahl, Roger Simm, Jannice Schau Slettemeås, Karin Lagesen, Madelaine Norström_

The aim of the study was to describe and compare the occurrence of quinolone resistant _E. coli_ in various animal species in relation to human population density. Data from 4568 _E. coli_ isolates from the Norwegian monitoring programme for antimicrobial resistance in feed, food and animals from 2006 to 2016 was compiled and analysed. The isolates originated from broilers, layers, cattle, turkeys, dogs, wild birds, red foxes, reindeer, sheep, horses and pigs. Data on the geographical location of origin for the isolates was available for 4050 isolates, and was used to categorize the isolates depending on the human population density of the area. In total, 1.4 % of the isolates were regarded as quinolone resistant, where the highest occurrence was in broilers and wild birds. Human population density was not associated with the occurrence of quinolone resistant _E. coli_. In Norway, fluoroquinolones are not used prophylactically and in almost negligent amounts in various species. This, and the observed interspecies variation, suggests other factors than fluoroquinolone use may be important in the development of quinolone resistant _E. coli_.

**2. Dissemination of quinolone resistant _Escherichia coli_ in the Norwegian broiler and pig production chain, and possible persistence in the broiler production environment**

_Håkon Kaspersen, Camilla Sekse, Eve Zeyl Fiskebeck, Jannice Schau Slettemeås, Roger Simm, Madelaine Norström, Anne Margrete Urdahl, Karin Lagesen_

In Norway, the use of quinolones in livestock populations is very low, and prophylactic use is prohibited. Despite this, quinolone resistant E. coli (QREC) are present at low levels in several animal species. The source of these QREC is unknown. The aim of this study was to characterize and compare QREC from different animal species to identify putative factors that may promote the occurrence of QREC. A total of 280 QREC isolates, from broilers, pigs, red foxes and wild birds, were whole genome sequenced and analysed. Well-known chromosomal and plasmid-mediated resistance mechanisms were identified. In addition, mutations in _marR_, _marA_ and _rpoB_ causing novel amino acid substitutions in their respective proteins were detected.  Phylogenetic analyses were used to determine the relationships between the isolates. Quinolone resistance mechanism patterns appeared to follow sequence type groups. Similar QREC isolates with similar resistance mechanism patterns were detected from the samples, and further phylogenetic analysis indicated close evolutionary relationships between specific isolates from different sources. This suggests dissemination of highly similar QREC isolates between animal species, and also persistence of QREC strains within the broiler production chain. This highlights the importance of both control measures at the top of the production chain, as well as biosecurity measures to avoid further dissemination and persistence of QREC in these environments. 

**3. Comparative genome analyses of wild type- and quinolone resistant _Escherichia coli_ indicate dissemination of QREC in the broiler production pyramid and potential sporadic local resistance development**

_Håkon Kaspersen, Eve Zeyl Fiskebeck, Camilla Sekse, Jannice Schau Slettemeås, Anne Margrete Urdahl, Madelaine Norström, Karin Lagesen, Roger Simm_

Quinolones are important antimicrobials for both humans and animals, and resistance towards these compounds is a serious threat to public health. In Norway, quinolone resistant E. coli (QREC) have been detected at low levels in a high proportion of broiler flocks, even without the use of quinolones in rearing of broilers. Due to the pyramidal structure of broiler breeding, QREC isolates may be disseminated from grandparent animals down through the pyramid. However, quinolone resistance can also develop in wild type E. coli through specific chromosomal mutations, and by horizontal acquisition of plasmid-mediated quinolone resistance genes. The goal of this study was to determine whether QREC is disseminated through the broiler breeding pyramid or developed locally at some stage in the broiler production chain. For this purpose, we whole genome sequenced wild type- and QREC isolates from broiler and parent flocks that had been isolated in the Norwegian monitoring program for antimicrobial resistance in feed, food and animals (NORM-VET) between 2006 and 2017, from 22 different production sites. The sequencing data was used for typing of the isolates, phylogenetic analysis and identification of relevant resistance mechanisms. Highly similar QREC isolates were identified within major sequence types from multiple production sites, suggesting dissemination of QREC isolates in the broiler production chain. The occurrence of potential resistance development among the WT E. coli was low, indicating that this may be a rare phenomenon in the Norwegian broiler production. The results indicate that the majority of the observed incidence of QREC at the bottom of the broiler production pyramid originates from parent or grandparent animals. These results highlight the importance of surveillance at all levels of the broiler production pyramid and of implementation of proper biosecurity measures to control dissemination of QREC. 