# Summary of scientific articles

**1. Occurrence of quinolone resistant _E. coli_ originating from different animal species in Norway**

The aim of the study was to describe and compare the occurrence of quinolone resistant _E. coli_ in various animal species in relation to human population density. Data from 4568 _E. coli_ isolates from the Norwegian monitoring programme for antimicrobial resistance in feed, food and animals from 2006 to 2016 was compiled and analysed. The isolates originated from broilers, layers, cattle, turkeys, dogs, wild birds, red foxes, reindeer, sheep, horses and pigs. Data on the geographical location of origin for the isolates was available for 4050 isolates, and was used to categorize the isolates depending on the human population density of the area. In total, 1.4 % of the isolates were regarded as quinolone resistant, where the highest occurrence was in broilers and wild birds. Human population density was not associated with the occurrence of quinolone resistant _E. coli_. In Norway, fluoroquinolones are not used prophylactically and in almost negligent amounts in various species. This, and the observed interspecies variation, suggests other factors than fluoroquinolone use may be important in the development of quinolone resistant _E. coli_.

**2. Closely related quinolone resistant Escherichia coli in different animal species in Norway – part of the normal flora or dissemination events?**

Emergence of quinolone resistant _Escherichia coli_ (QREC) has been attributed to dissemination of exogenous strains or the spontaneous development of resistance in the intestinal microbiota. In Norway, QREC has been detected in a high proportion of samples from various animal species. This was unexpected, as the usage of quinolones in Norwegian livestock is regarded as negligible, and the source of this emergence is currently unknown. Additionally, there is limited knowledge of the quinolone resistance mechanisms in QREC from animal origin in Norway. The aim of this study was to characterize quinolone resistance mechanisms present in QREC from different animal species, and to use this information in a population structure context to identify possible dissemination of QREC strains. A total of 285 QREC isolates, originating from broilers, pigs, red foxes and wild birds, were whole-genome sequenced. Contaminant reads were identified with mash screen. Raw reads were quality controlled with fastQC, excess PhiX removed with bbduk, trimmed with trimmomatic and assembled with SPAdes. Assemblies were error corrected with pilon. Sequence types and quinolone resistance gene prediction was done with ARIBA. ChewBBACA was used to call the core genome multi locus sequence typing (cgMLST) variants. Dendrograms were calculated from distances between isolates from the cgMLST results. 
The identified quinolone resistance mechanisms were concordant with previously described mechanisms. Some of the isolates had less than or equal to ten allele differences in cgMLST compared to other isolates within the same sequence type. Resistance mechanisms were homogenously distributed within major sequence types, with the exception of ST10 and ST58. Isolates from broilers had a lower intra-species distance than isolates from other animal species.
A high diversity was seen in the QREC population structure. Nonetheless, similar QREC isolates were detected in multiple species with similar resistance mechanism patterns. This indicates dissemination events of similar QREC isolates between animal species, and also within the broiler production pyramid.


**3. Broiler article**

Text goes here
