--- 
title: "Comparative genomics of quinolone resistant E. coli from animal sources - The application of bioinformatics..."
subtitle: "Thesis for the degree of Philosophiae Doctor (PhD)"
author: "Håkon Kaspersen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
geometry: "left=4cm,right=3cm,top=3cm,bottom=3cm"
subparagraph: true
output:
  bookdown::pdf_book:
    citation_package: natbib
    includes:
      before_body: frontpage.tex
      in_header: preamble.tex
fontsize: 12pt
linestretch: 1.2
toc-depth: 1
toc-bib: true
lof: TRUE
documentclass: book
bibliography: [packages.bib, library.bib]
biblio-style: apalike
link-citations: yes
---

```{r include=FALSE}
# automatically create a bib database for R packages

packages <- c("bookdown","knitr","rmarkdown","tidyverse")

knitr::write_bib(c(.packages(), packages), 'packages.bib')
```

# Acknowledgements
I would like to thank...

# Disclosure
This thesis was written in RStudio with `r version$version.string` using the Bookdown package [@R-bookdown].

# Funding
This project was funded by the Norwegian Research Council (NFR no. 255383) and the Norwegian food industry.

# Summary (English)


# Summary (Norwegian)

# Abbreviations
- QREC: Quinolone Resistant _Escherichia coli_
- AMR: Antimicrobial Resistance
- WGS: Whole Genome Sequencing
- MDR: Multi Drug Resistance


# List of publications

1. **Occurrence of quinolone resistant _E. coli_ originating from different animal species in Norway**. Håkon Kaspersen, Anne Margrete Urdahl, Roger Simm, Jannice Schau Slettemeås, Karin Lagesen, Madelaine Norström (2018). _Veterinary Microbiology_, 217(February):25-31. (10.1016/j.vetmic.2018.02.022).

2. **Closely related quinolone resistant Escherichia coli in different animal species in Norway – part of the normal flora or dissemination events?**
Håkon Kaspersen, Camilla Sekse, Jannice Schau Slettemeås, Roger Simm, Anne Margrete Urdahl, Madelaine Norström, Karin Lagesen.

3. **Broiler study**